### ISSUE TITLE
Overlay not recognozing/showing Baron/Dragon timers

### ISSUE THREAD

**Issue by DeathlezzLoL** [finncyr/ECO-League-Overlay#3]
So I was testing because I looked forward to use this tool because is the only one that shows baron and dragon timers, tried a few things but it isnt showing anything at all on my OBS, need help pls

**Comment by finncyr** [comment]
There is an Option to Activate the Neutral Baron and Drake timers in the game itself, therefore i stopped working on it.

I can't tell you exactly what to do, due to Riot Legel Jibberish, but with the help of Google you should find a way to activate this in the spectator config.
